### PR TITLE
Hum 47 bad validation when setting up operator

### PR DESCRIPTION
**Pull request by KacperKoza343**
## Description

HUM-47

### CODE REVIEW

**Review by portuu3 — DISMISSED** [review]

**Review by portuu3 — DISMISSED** [review]

**Comment by KacperKoza343** [comment]
> @KacperKoza343 could you please update this branch with latest `develop`? It's necessary to have it in order to test after some recent changes

done

**Review by dnechay — COMMENTED** [review]
Seems like something went wrong during url validation discussion 😅 

IMU we don't need to enforce http(s) (i.e. if entered - considered valid, but need to make sure that the whole string is valid URL.
E.g., webhook url can be something like `https://webhool-consumer.io/webhooks/hp?someParam=someValue`

You can achieve that either by custom function around URL or by using some smart regex

**Comment by mpblocky** [comment]
@dnechay changes were added, ready for CR

**Review by dnechay — COMMENTED** [review]
LGTM

One question before approval: is it high effort to change the behavior of operator form to validate values in live, i.e. once you start input, not waiting for "Add new Keys ..." click?
It is already reactive after you click this button, but would be nice to inform the user in live mode

**Comment by mpblocky** [comment]
@dnechay it seems for me that sadly it's not a simple switch for that, as I see the form validation is pretty complicated. We surely can do that, however I warn that it might take some time. Should we proceed with the PR as is or should we change to live validation?

**Comment by dnechay** [comment]
@mpblocky it's "nice to have" not "must have", so can be done later if needed 👌🏼

**Pull request merged**
