### PR TITLE
add all deployed networks and maintainers in core/readme

### PR DESCRIPTION
**Pull request by foufrix**
## Description

Re-add lost maintainers & address contracts on all networks during repo migrations.

## Summary of changes

Add contracts address on all networks and maintainers

## How test the changes

Check contracts on all explorers

### CODE REVIEW

**Comment by foufrix** [comment]
I've also added @hrik2001 avalanche deployment related to https://github.com/humanprotocol/human-protocol/pull/158

**Comment by portuu3** [comment]
We already have a file containing contract addresses https://github.com/humanprotocol/human-protocol/blob/main/CONTRACTS_LIST.md
Can you check and combine your file into this?

**Comment by foufrix** [comment]
> @foufrix we already have a file containing contract addresses https://github.com/humanprotocol/human-protocol/blob/main/CONTRACTS_LIST.md Can you check and combine your file into this?

@portuu3  ok will double check, where do you want to track name and github profile of maintainers now?

**Comment by portuu3** [comment]
> > @foufrix we already have a file containing contract addresses https://github.com/humanprotocol/human-protocol/blob/main/CONTRACTS_LIST.md Can you check and combine your file into this?
> 
> @portuu3 ok will double check, where do you want to track name and github profile of maintainers now?

I think I would use a file CONTRIBUTORS.md in the root folder, so you dont need search inside folders to find it

**Comment by foufrix** [comment]
Hi @portuu3, I've made the changes you requested.
I added all KVstore that are already deployed and were not ported to this file.
I updated the HMT address on Mumbai. It was not the good one (inexistent, was a copy of the moonbeam address) [here is the good one](https://mumbai.polygonscan.com/address/0x0376D26246Eb35FF4F9924cF13E6C05fd0bD7Fb4)

**Review by portuu3 — APPROVED** [review]

**Pull request merged**
