### PR TITLE
[escrow-dashboard] improve escrow-dashboard ui

### PR DESCRIPTION
**Pull request by m00n620**
- Hide MyHMT button because it is in WIP.
- Fixed all margins/paddings and icons on escrow-dashboard home page
- Add bottom border at networks tab.
- Fixed the tooltip for the stacked bar chart.
- Fixed tick styles for all bar charts.
- Fixed the leaderboard table styles.

Here's the figma link - https://www.figma.com/file/u81GKebVavmQW8zGHb5Jgo/Dashboards---Everything-Apps?type=design&node-id=1392-14794&t=iBTAgCuWP674hqxt-0

### CODE REVIEW

**Comment by m00n620** [comment]
> @m00n620 please add info about the changes to be implemented or a figma design

Updated the description with Figma link, @portuu3

**Review by portuu3 — CHANGES_REQUESTED** [review]
When I swithc the network and metamask is connected it asks for approval in metamask.
Also you are missing the see more button 
image
Time period selector missing in barcharts

**Comment by m00n620** [comment]
> When I swithc the network and metamask is connected it asks for approval in metamask. Also you are missing the see more button image Time period selector missing in barcharts

- I think we need to ask users to change his network on metamask because he will do make transactions later
- we don't need See More button for token view because we don't have any detail pages for tokens
- time period selector will be done in separate branch
@portuu3

**Comment by portuu3** [comment]
```
I think we need to ask users to change his network on metamask because he will do make transactions later
```
I mean with this network selector 
image

**Comment by portuu3** [comment]
should it look like this? 
image

**Review by portuu3 — APPROVED** [review]

**Pull request merged**
