### PR TITLE
(HUM-70): align chat icon with figma

### PR DESCRIPTION
**Pull request by mpblocky**
## Description

HUM-70

### CODE REVIEW

**Review by dnechay — CHANGES_REQUESTED** [review]
-  Linter is failing, please check
- It's seems broken on my laptop for local and vercel envs (see screenshot)
Screenshot 2024-10-30 at 18 08 15

Please make sure you test your changes carefully before you provide the code for review.
Ideally if it's some sort of visual changes - please provide some screenshots about what exactly change and how it looks like, so it's easier to check the expectations

**Comment by mpblocky** [comment]
@dnechay sure, will provide screenshot for every visual change from now on. Sorry for missing the linter, I'm not sure how this wasn't displayed in my editor 😅
As for the testing, we test every PR including this; it's surprising to me that this happened. Can You sent me the exact dimensions to include it in the testing stage? In the meantime I will try to fix that.

**Comment by mpblocky** [comment]
Should be good now (I suspect the scrolls appeared on Your screen because of the thing that linter pointed out):
image
image

**Comment by dnechay** [comment]
@mpblocky indeed, probably related to it because I was testing with also switching modes

**Review by dnechay — APPROVED** [review]

**Pull request merged**
