### PR TITLE
[WIP] project: remove basemodels

### PR DESCRIPTION
**Pull request by pared-imi**
## Description

Get rid of `human-protocol-basemodels` duplicating `hmt-basemodels` repository.

## Summary of changes

Removing occurrences of `human-protocol-basemodels` across the project.

## How test the changes

`make generate-json` from `packages/sdk/python/human-protocol-basemodels` should still work as intended, as it will generate json schema from `hmt-basemodels`, if it is installed in python that is used by schema generating script.

## Related issues
[Keywords for linking issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

#187 
#205 

## Operational checklist

- [X] All new functionality is covered by tests
- [ ] Any related documentation has been changed or added

TODO:
- [ ] create README.md in `human-protocol-basemodels` and explain how to use `human-protocol-sdk` dependencies to generate JSON schema

## Note to reviewers
This is my first contribution to this repository. To my best knowledge, this change doesn't brake existing tests and forces this project to use the existing library `hmt-basemodels` instead of its copied version. When looking at #205 change, it seems to me that we are using `JSON` schema to generate typescript schemas. `JSON` schema could be obtained from `hmt-basemodels` instead of `human-protocol-basemodels`. Do this project and its derivatives have some additional requirements that cannot be covered by `hmt-basemodels`?

### CODE REVIEW

**Comment by leric7** [comment]
@pared-imi , As far as I know, we will archive hmt-basemodels repo from hCaptcha, and manage basemodels from monorepo moving forward. cc, @posix4e

**Comment by posix4e** [comment]
hopefully yes

**Comment by pared-imi** [comment]
@leric7 @posix4e So that means that we will have to maintain 2 copies of `basemodels`? Or will `humanprotocl` depend on monorepo? (Or other way around?)

**Comment by posix4e** [comment]
less copies is always good

**Comment by pared-imi** [comment]
I understood from an internal conversation that the `basemodels` diverged somewhere around the `1.1.1` version. I am closing this PR for now. I will introduce my changes in a separate PR.

**Pull request closed without merging**
